sudo apt-get install --reinstall libopencv-videostab4.2:amd64
sudo apt-get install --reinstall libopencv-core4.2:amd64
sudo apt-get install --reinstall libopencv-dnn4.2:amd64
sudo apt-get install --reinstall libopencv-imgproc4.2:amd64
sudo apt-get install --reinstall libopencv-videoio4.2:amd64
sudo apt-get install --reinstall libopencv-imgcodecs4.2:amd64
sudo apt-get install --reinstall libopencv-imgcodecs-dev:amd64
sudo apt-get install --reinstall libopencv-highgui4.2:amd64
sudo apt-get install --reinstall libopencv-features2d4.2:amd64
sudo apt-get install --reinstall libopencv-superres4.2:amd64
sudo apt-get install --reinstall libopencv-objdetect4.2:amd64
sudo apt-get install --reinstall libopencv-imgproc-dev:amd64
sudo apt-get install --reinstall libopencv-stitching4.2:amd64
sudo apt-get install --reinstall libopencv-calib3d4.2:amd64
sudo apt-get install --reinstall libopencv-core-dev:amd64
sudo apt-get install --reinstall libopencv-highgui-dev:amd64
sudo apt-get install --reinstall libopencv-flann4.2:amd64
sudo apt-get install --reinstall libopencv-videoio-dev:amd64
sudo apt-get install --reinstall libopencv-photo4.2:amd64
sudo apt-get install --reinstall libopencv-contrib4.2:amd64
sudo apt-get install --reinstall libopencv-shape4.2:amd64
sudo apt-get install --reinstall libopencv-video4.2:amd64
sudo apt-get install --reinstall libopencv-viz4.2:amd64
sudo apt-get install --reinstall libopencv-ml4.2:amd64
